### ISSUE TITLE
Cutting and Undoing many objects fails

### ISSUE THREAD

**Issue by hasii2011** [hasii2011/PyUt#396]
```
Traceback (most recent call last):
  File "/Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/src/org/pyut/ui/frame/EditMenuHandler.py", line 69, in onUndo
    historyManager.undo()
  File "/Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/src/org/pyut/history/HistoryManager.py", line 122, in undo
    group.undo()
  File "/Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/src/org/pyut/history/commands/CommandGroup.py", line 167, in undo
    command.undo()
  File "/Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/src/org/pyut/history/commands/DelOglLinkCommand.py", line 79, in undo
    self._shape = umlFrame.createLink(src=src, dst=dest, linkType=self._linkType)
  File "/Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/src/org/pyut/ui/UmlClassDiagramsFrame.py", line 78, in createLink
    destinationClass: PyutClass = cast(PyutClass, dst.pyutObject)
AttributeError: 'NoneType' object has no attribute 'pyutObject'

```

**Comment by hasii2011** [comment]
This issue #435;  Means I won't waste time fixing this
