### ISSUE TITLE
Make a standalone app

### ISSUE THREAD

**Issue by hasii2011** [hasii2011/PyUt#6]
use py2App

**Comment by hasii2011** [comment]
Moving to release 3.5 because still cannot figure out why Mac app is failing

**Comment by hasii2011** [comment]
Hmm.  App runs in _alias_ mode, but errors with weird error in _deployment_ mode with error

`NSOSStatusErrorDomain Code=-67062`

**Comment by hasii2011** [comment]
I don't think it is a code-signing problem anymore.  w/o code signing attempt, I get this:

Traceback (most recent call last):
  File "/Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/dist/Pyut.app/Contents/Resources/__boot__.py", line 98, in <module>
    _run()
  File "/Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/dist/Pyut.app/Contents/Resources/__boot__.py", line 82, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/dist/Pyut.app/Contents/Resources/Pyut.py", line 14, in <module>
    from org.pyut.PyutUtils import PyutUtils
  File "org/pyut/PyutUtils.pyc", line 11, in <module>
  File "wx/__init__.pyc", line 17, in <module>
  File "wx/core.pyc", line 12, in <module>
  File "wx/_core.pyc", line 14, in <module>
  File "wx/_core.pyc", line 10, in __load
  File "imp.pyc", line 342, in load_dynamic
ImportError: dlopen(/Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/dist/Pyut.app/Contents/Resources/lib/python3.7/lib-dynload/wx/_core.so, 2): Library not loaded: @loader_path/libwx_osx_cocoau_core-3.0.0.4.0.dylib
  Referenced from: /Users/humberto.a.sanchez.ii/PycharmProjects/PyUt/dist/Pyut.app/Contents/Resources/lib/python3.7/lib-dynload/wx/_core.so
  Reason: image not found
2020-01-07 16:55:03.182 Pyut[1248:34984] Pyut Error

**Comment by hasii2011** [comment]
Looked at py2app's bitbucket account and found this:

https://bitbucket.org/ronaldoussoren/py2app/issues/254/traceback-reason-image-not-found-on-mac

**Comment by hasii2011** [comment]
Going to close this as _partially complete_.  As I said, in the FAQ I am having code-signing problems.  I'll point this this from the new issue;  I documented a _hack_ on how to get Pyut to run outside of Pycharm
